export const SECTIONS = [
  {
    id: 'identification',
    title: 'Identification',
    icon: '👤',
    color: '#0D1B2A',
    fields: [
      { id: 'nom',      label: 'Nom complet',       type: 'text',   required: true,  placeholder: 'Prénom NOM' },
      { id: 'email',    label: 'Email UM6P',         type: 'email',  required: true,  placeholder: 'prenom.nom@um6p.ma' },
      { id: 'grade',    label: 'Grade académique',   type: 'select', required: true,
        options: ['Assistant Professor', 'Associate Professor', 'Full Professor', 'Professeur Invité'] },
      { id: 'semestre', label: 'Semestre de saisie', type: 'select', required: true,
        options: ['S1 — 2024/2025', 'S2 — 2024/2025', 'S1 — 2025/2026', 'S2 — 2025/2026'] },
      { id: 'orcid',    label: 'ORCID',              type: 'text',   required: false, placeholder: '0000-0000-0000-0000' },
    ],
  },
  {
    id: 'production',
    title: 'Production scientifique',
    icon: '🔬',
    color: '#047481',
    fields: [
      { id: 'pub_soumises',  label: 'Publications soumises ce semestre',  type: 'number', required: true,  hint: 'Total ce semestre' },
      { id: 'pub_acceptees', label: 'Publications acceptées',             type: 'number', required: true },
      { id: 'pub_q1q2',      label: 'Dont publications Q1/Q2',            type: 'number', required: false },
      { id: 'pub_final',     label: 'Publications publiées (Final)',       type: 'number', required: false },
      { id: 'citations',     label: 'Citations reçues (Scopus)',           type: 'number', required: false },
      { id: 'open_access',   label: 'Publications Open Access',           type: 'number', required: false },
      { id: 'type_oa',       label: "Type d'accès libre principal",       type: 'select', required: false,
        options: ['Aucun', 'Gold Open Access', 'Green Open Access', 'Hybrid Gold', 'Diamond OA'] },
      { id: 'livres',        label: 'Livres & chapitres publiés',         type: 'number', required: false },
      { id: 'refs_biblio',   label: 'Références bibliographiques',        type: 'textarea', required: false,
        placeholder: 'Auteurs, titre, journal, DOI — une publication par ligne', hint: 'Optionnel' },
    ],
  },
  {
    id: 'projets',
    title: 'Projets & Rayonnement',
    icon: '💰',
    color: '#057A55',
    fields: [
      { id: 'projets_soumis',   label: 'Projets de recherche soumis',        type: 'number', required: true },
      { id: 'projets_obtenus',  label: 'Projets de recherche obtenus',       type: 'number', required: true },
      { id: 'budget_mad',       label: 'Budget obtenu (MAD)',                 type: 'number', required: false, hint: "Projets acceptés dont vous êtes PI/co-PI" },
      { id: 'projets_internat', label: 'Projets internationaux',             type: 'number', required: false },
      { id: 'financement',      label: 'Type de financement principal',       type: 'select', required: false,
        options: ['Aucun', 'National (CNRST, OCP…)', 'International (EU, World Bank…)', 'Industriel', 'Institutionnel UM6P', 'Bilatéral'] },
      { id: 'role_projet',      label: 'Rôle dans le(s) projet(s)',          type: 'select', required: false,
        options: ['PI (Principal Investigator)', 'Co-PI', 'Participant', 'Coordinateur', 'Consultant'] },
      { id: 'conferences_int',  label: 'Conférences internationales',        type: 'number', required: false },
      { id: 'comm_invitees',    label: 'Communications invitées',            type: 'number', required: false },
      { id: 'brevets_deposes',  label: 'Brevets déposés',                    type: 'number', required: false },
      { id: 'brevets_acceptes', label: 'Brevets acceptés',                   type: 'number', required: false },
      { id: 'prototypes',       label: 'Prototypes / Transferts TRL',        type: 'number', required: false },
      { id: 'trl',              label: 'Niveau TRL principal',               type: 'select', required: false,
        options: ['N/A', 'TRL 1', 'TRL 2', 'TRL 3', 'TRL 4', 'TRL 5', 'TRL 6', 'TRL 7', 'TRL 8', 'TRL 9'] },
    ],
  },
  {
    id: 'formation',
    title: 'Formation & Prestations',
    icon: '👥',
    color: '#5521B5',
    fields: [
      { id: 'h_initiale',  label: 'H. Formation initiale',           type: 'number', required: true,  hint: 'Cours, TD, TP — licence / master' },
      { id: 'h_executive', label: 'H. Formation exécutive',          type: 'number', required: false, hint: 'Formation continue, executive education' },
      { id: 'h_doctorale', label: 'H. Formation doctorale',          type: 'number', required: false, hint: 'Écoles doctorales, séminaires de recherche' },
      { id: 'doctorants',  label: 'Doctorants encadrés (total)',     type: 'number', required: true,  hint: 'Tous en cours — directeur ou co-directeur' },
      { id: 'theses_sout', label: 'Thèses soutenues ce semestre',    type: 'number', required: false },
      { id: 'pfe',         label: 'PFE / Masters encadrés',          type: 'number', required: false },
      { id: 'nb_presta',   label: 'Nb. prestations de service',      type: 'number', required: false },
      { id: 'revenus_mad', label: 'Revenus prestations (MAD)',        type: 'number', required: false },
      { id: 'type_presta', label: 'Type de prestation principal',    type: 'select', required: false,
        options: ['Aucune', 'Expertise technique', 'Audit / Diagnostic', 'Formation continue', 'Consulting', 'Étude de faisabilité', 'Autre'] },
    ],
  },
  {
    id: 'bilan',
    title: 'Bilan & Commentaires',
    icon: '📋',
    color: '#B45309',
    fields: [
      { id: 'statut_obj',    label: 'Avez-vous atteint vos objectifs ?',      type: 'select',   required: true,
        options: ['Oui, atteints ou dépassés', 'Partiellement (75–99%)', 'Non atteint (< 75%)', 'Objectifs non définis'] },
      { id: 'justif_ecarts', label: 'Justification des écarts (si ≥ 20%)',    type: 'textarea', required: false,
        placeholder: 'Expliquer les raisons des écarts entre objectifs et réalisations...' },
      { id: 'faits_marq',    label: 'Faits marquants du semestre',            type: 'textarea', required: false,
        placeholder: 'Prix, nouvelles collaborations, événements importants...' },
      { id: 'actions_corr',  label: 'Actions correctives prévues',            type: 'textarea', required: false,
        placeholder: 'Mesures pour le prochain semestre...' },
      { id: 'besoins',       label: 'Besoins de support (Direction)',         type: 'textarea', required: false,
        placeholder: 'Ressources, équipements, budget, formations souhaités...' },
      { id: 'perspectives',  label: 'Perspectives — prochain semestre',       type: 'textarea', required: false,
        placeholder: 'Publications prévues, projets à soumettre, conférences...' },
    ],
  },
]

export const ALL_FIELDS = SECTIONS.flatMap(s => s.fields.map(f => ({ ...f, section: s.id })))
export const FIELD_IDS  = ALL_FIELDS.map(f => f.id)
export const FIELD_LABELS = ALL_FIELDS.map(f => f.label)
